### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by ckknight** [dispix/react-pirate#1]
I noticed that the `package.json` specifies the license as "ISC", but there is no corresponding `LICENSE` file.

I'm also aware that ISC is the default when running `npm init`, so it might not be intended.

Of course it's up to you, but I'm a fan of using the same license as React itself ([MIT](https://github.com/facebook/react/blob/master/LICENSE)).

**Comment by dispix** [comment]
Hi ! Thanks for the insight. You're right about the ISC choice, it's just the npm default so I updated the license to MIT.
